faker_for_df = {
    "country":
    [
        "Gibraltar",
        "Korea",
        "Cocos (Keeling) Islands",
        "Estonia",
        "Moldova",
        "Georgia",
        "Pakistan",
        "Equatorial Guinea",
        "Sudan",
        "Hungary",
        "Canada",
        "Cayman Islands",
        "Philippines",
        "Kenya",
        "Christmas Island",
        "Croatia",
        "Turkey",
        "Liechtenstein",
        "Wallis and Futuna",
        "Central African Republic",
        "Hungary",
        "Mozambique",
        "Jersey",
        "Paraguay",
        "Turkmenistan",
        "Morocco",
        "Nicaragua",
        "Iran",
        "Vietnam",
        "Uruguay",
        "Iran",
        "Aruba",
        "Antarctica",
        "Venezuela",
        "Russian Federation",
        "Bolivia",
        "Madagascar",
        "Christmas Island",
        "Christmas Island",
        "Sudan",
        "Niger",
        "Canada",
        "Sierra Leone"
    ],
    "year":
        [
            2007,
            1980,
            1998,
            2010,
            2002,
            1950,
            1950,
            2010,
            1963,
            2017,
            1968,
            1951,
            1981,
            1955,
            1969,
            2011,
            1961,
            2013,
            1974,
            2020,
            1953,
            1986,
            2022,
            1962,
            2020,
            1993,
            2013,
            1959,
            2003,
            1954,
            1964,
            1951,
            1962,
            1980,
            1987,
            1970,
            1990,
            2013,
            1974,
            1976,
            1952,
            1972,
            1978
        ],
    "address":
    [
        "https://docs.google.com/presentation/d/e/2PACX-1V6dseGWm7NoSZxUx9-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NO90Tr&geTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-HapQ593dIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQUc_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliMt6pltyBoS-K78Tald0EWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIB_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDdv64cGg0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0v6d4Gct35dD_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEaslkje4oiuekjQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-ame5Db9WwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTm3Dxr4WSf-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-m934BmgbTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7me4Dvg-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-mt68aWvWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1V6dseGWm7NoSZxUx9-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NO90Tr&geTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-HapQ593dIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQUc_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliMt6pltyBoS-K78Tald0EWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIB_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDdv64cGg0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0v6d4Gct35dD_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEaslkje4oiuekjQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-ame5Db9WwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTm3Dxr4WSf-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-m934BmgbTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvImaR_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1V6dseGWm7NoSZxUx9-dMZi0NZWm57wGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NO90Tr&geTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-HapQ593dIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQUc_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliMt6pltyBoS-K78Tald0EWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIB_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDdv64cGg0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0v6d4Gct35dD_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEaslkje4oiuekjQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-ame5Db9WwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTm3Dxr4WSf-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-m934BmgbTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1V6dseGWm7NoSZxUx9-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NO90Tr&geTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-HapQ593dIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQUc_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliMt6pltyBoS-K78Tald0EWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIB_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vbMkkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDdv64cGg0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0v6d4Gct35dD_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEaslkje4oiuekjQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTWm7NoSZxU-ame5Db9mt4hwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-1vRvJkliTm3Dxr4WSf-dMZi0NZWwIhwGWTbP2WU2LZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        "https://docs.google.com/presentation/d/e/2PACX-m934BmgbTWm7NoSZxU-dMZi0NZWwIhwGWTbP2Wmy3ZykmUDNceEX3f0HQ0mYVvIBQU_OkNsnlVnyZkP5/pub?start=false&loop=false&delayms=60000",
        
    ],
    "treat":
    [
        "jujubes",
        "ice_cream",
        "chocolate",
        "candy_cane",
        "cake",
        "cotton_candy",
        "halva",
        "chupa_chups",
        "tiramisu",
        "chocolate",
        "blueberry_muffin",
        "baklava",
        "sugar_cookie",
        "cotton_candy",
        "gummi_bears",
        "baklava",
        "wafer",
        "brownie",
        "cotton_candy",
        "cotton_candy",
        "jelly_beans",
        "jelly_beans",
        "baklava",
        "oat_cake",
        "sweet_roll",
        "sweet_roll",
        "powder",
        "candy_canes",
        "candy_canes",
        "shortbread",
        "souffle",
        "brownie",
        "liquorice",
        "marzipan",
        "gingerbread",
        "gingerbread",
        "bonbon",
        "tiramisu",
        "jelly",
        "sugar_plum",
        "sugar_plum",
        "donut",
        "caramels"
    ],
    "color":
    [
        "Purple",
        "BlanchedAlmond",
        "MediumSeaGreen",
        "WhiteSmoke",
        "RoyalBlue",
        "MediumPurple",
        "MediumSeaGreen",
        "Plum",
        "MediumSeaGreen",
        "MediumPurple",
        "PeachPuff",
        "PeachPuff",
        "Magenta",
        "YellowGreen",
        "DarkKhaki",
        "MistyRose",
        "White",
        "LightGreen",
        "Tan",
        "DimGray",
        "DarkSlateBlue",
        "PowderBlue",
        "GreenYellow",
        "Wheat",
        "DarkTurquoise",
        "DeepPink",
        "MediumSlateBlue",
        "ForestGreen",
        "GhostWhite",
        "PeachPuff",
        "PeachPuff",
        "SlateGray",
        "Crimson",
        "SandyBrown",
        "OrangeRed",
        "Chartreuse",
        "PeachPuff",
        "Salmon",
        "Khaki",
        "HotPink",
        "LimeGreen",
        "SaddleBrown",
        "Orange"
    ],
    "2nd_clue":
    [
        "the 'treats' value is 'gingerbread' and the 'colors' value is 'MediumSlateBlue'",
        "the 'treats' value is 'marzipan' and the 'colors' value is 'HotPink'",
        "the 'treats' value is 'tiramisu' and the 'colors' value is 'MediumSeaGreen'",
        "the 'treats' value is 'gingerbread' and the 'colors' value is 'MistyRose'",
        "the 'treats' value is 'gingerbread' and the 'colors' value is 'HotPink'",
        "the 'treats' value is 'sugar_plum' and the 'colors' value is 'GreenYellow'",
        "the 'treats' value is 'chupa_chups' and the 'colors' value is 'LimeGreen'",
        "the 'treats' value is 'brownie' and the 'colors' value is 'DeepPink'",
        "the 'treats' value is 'halva' and the 'colors' value is 'HotPink'",
        "the 'treats' value is 'gummi_bears' and the 'colors' value is 'MediumSeaGreen'",
        "the 'treats' value is 'blueberry_muffin' and the 'colors' value is 'DarkTurquoise'",
        "the 'treats' value is 'gummi_bears' and the 'colors' value is 'Orange'",
        "the 'treats' value is 'candy_canes' and the 'colors' value is 'Plum'",
        "the 'treats' value is 'cotton_candy' and the 'colors' value is 'OrangeRed'",
        "the 'treats' value is 'cotton_candy' and the 'colors' value is 'SaddleBrown'",
        "the 'treats' value is 'danish' and the 'colors' value is 'MediumSeaGreen'",
        "the 'treats' value is 'brownie' and the 'colors' value is 'White'",
        "the 'treats' value is 'brownie' and the 'colors' value is 'LimeGreen'",
        "the 'treats' value is 'jelly_beans' and the 'colors' value is 'DarkKhaki'",
        "the 'treats' value is 'ice_cream' and the 'colors' value is 'LightGreen'",
        "the 'treats' value is 'chupa_chups' and the 'colors' value is 'Salmon'",
        "the 'treats' value is 'gingerbread' and the 'colors' value is 'HotPink'",
        "the 'treats' value is 'donut' and the 'colors' value is 'DimGray'",
        "the 'treats' value is 'jelly_beans' and the 'colors' value is 'MediumSlateBlue'",
        "the 'treats' value is 'cotton_candy' and the 'colors' value is 'Orange'",
        "the 'treats' value is 'donut' and the 'colors' value is 'HotPink'",
        "the 'treats' value is 'sweet_roll' and the 'colors' value is 'Crimson'",
        "the 'treats' value is 'sugar_plum' and the 'colors' value is 'MediumPurple'",
        "the 'treats' value is 'candy_canes' and the 'colors' value is 'MediumSlateBlue'",
        "the 'treats' value is 'cotton_candy' and the 'colors' value is 'GhostWhite'",
        "the 'treats' value is 'gingerbread' and the 'colors' value is 'Salmon'",
        "the 'treats' value is 'tiramisu' and the 'colors' value is 'SandyBrown'",
        "the 'treats' value is 'jelly_beans' and the 'colors' value is 'DimGray'",
        "the 'treats' value is 'candy_cane' and the 'colors' value is 'PowderBlue'",
        "the 'treats' value is 'ice_cream' and the 'colors' value is 'LightGreen'",
        "the 'treats' value is 'danish' and the 'colors' value is 'LightGreen'",
        "the 'treats' value is 'jelly_beans' and the 'colors' value is 'Chartreuse'",
        "the 'treats' value is 'blueberry_muffin' and the 'colors' value is 'DarkKhaki'",
        "the 'treats' value is 'bonbon' and the 'colors' value is 'DimGray'",
        "the 'treats' value is 'jelly_beans' and the 'colors' value is 'MediumPurple'",
        "the 'treats' value is 'souffle' and the 'colors' value is 'SandyBrown'",
        "the 'treats' value is 'baklava' and the 'colors' value is 'PeachPuff'",
        "the 'treats' value is 'chocolate' and the 'colors' value is 'DeepPink'"
    ],
}